name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  core-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: pnpm build --filter "*/core"

      - name: Lint
        run: pnpm lint --filter "*/core"

      - name: Type Check
        run: pnpm type-check --filter "*/core"

  cli-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Build
        run: pnpm build --filter "*/cli"

      - name: Lint
        run: pnpm lint --filter "*/cli"

      - name: Type Check
        run: pnpm type-check --filter "*/cli"
